JobPortal.App/Controllers/JobController.cs
using JobPortal.App.App_Start;
using JobPortal.App.Models;
using JobPortal.Models.Enums;
using JobPortal.Models.Implementation;
using JobPortal.Models.ViewModels;
using JobPortal.Repository.Contract;
using JobPortal.Services.Contract;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.App.Controllers
{
    [Authorize]
    [UsageLoggingFilterAttribute]
    public class JobController : Controller
    {
        private IJobService jobService;
        IJobApplicationService jobApplicationService;
        private ApplicationUserManager userManager;
        private IUnitOfWork uow;
        public JobController(IUnitOfWork _uow, IJobService _jobService, ApplicationUserManager _userManager, IJobApplicationService _jobAppService)
        {
            jobService = _jobService;
            userManager = _userManager;
            jobApplicationService = _jobAppService;
            uow = _uow;
        }

        #region index commented

        [AllowAnonymous]
        // GET: Job
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, string state, string category, int? page, JobSearchModel jsmodel = null)
        {
            return RedirectToAction("S");
            /*
            //check if it's ajax result ==> return the list and update only the list section            
       
            ViewBag.CurrentSort = sortOrder;
            ViewBag.PopularSortParm = "popular";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.SalarySortParm = "salary_desc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var model = uow.jobRepository.GetAll();

            if (Request.IsAjaxRequest())
            {
                Dictionary<string, object> searchObj = JobModelToDict(jsmodel);
                model = jobService.FindJob(searchObj);
                return PartialView("_JobList", model.ToList());
            }
            else if (!(String.IsNullOrEmpty(searchString) || string.IsNullOrEmpty(state) || String.IsNullOrEmpty(category)))
            {
                jsmodel = new JobSearchModel { SearchString = searchString, Category = category, State = state };
                Dictionary<string, object> searchObj = JobModelToDict(jsmodel);
                model = jobService.FindJob(searchObj);
            }


            switch (sortOrder)
            {
                case "salary_desc":
                    model = model.OrderByDescending(s => s.MaximumSalary);
                    break;
                case "popular":
                    model = model.OrderByDescending(s => s.NumberOfApplicants);
                    break;
                case "Date":
                    model = model.OrderBy(s => s.DatePosted);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(s => s.DatePosted);
                    break;
                default:  // Name ascending 
                    model = model.OrderByDescending(s => s.DatePosted);
                    break;
            }

           

            ViewBag.JobCatId = uow.jobCategoryRepository.GetAll().AsEnumerable()
                .Select(j => new SelectListItem { Text = j.Name, Value = Convert.ToString(j.Jobs.Count()) });
            ViewBag.State = CountryStates.GetStates("Nigeria");
            ViewBag.Companies = uow.companyRepository.GetAll().Select(c => c.Name);
            ViewBag.JobType = Enum.GetValues(typeof(JobType));
            ViewBag.ExperienceLevel = Enum.GetValues(typeof(ExperienceLevel));


            int pageSize = 10;
            int pageNumber = (page ?? 1);

            int jobStartNum = GetJobStart(pageNumber, pageSize);
            int jobEndNum = GetJobEnd(model.Count(), pageNumber, pageSize, jobStartNum);
            ViewBag.StartIndex = jobStartNum;
            ViewBag.EndIndex = jobEndNum;
            ViewBag.ModelCount = model.Count();
            return View(model.ToPagedList(pageNumber, pageSize));
            */
        }

        #endregion

        [AllowAnonymous]
        public ActionResult S(string o, string f, string s, string st, string ct, int? p, JobSearchViewModel jsmodelkk, JobListVM vm)
        {
            ViewBag.CurrentSort = o;
            ViewBag.PopularSortParm = "popular";
            ViewBag.DateSortParm = o == "Date" ? "date_desc" : "Date";
            ViewBag.SalarySortParm = "salary_desc";

            if (s != null)
            {
                p = 1;
            }
            else
            {
                s = f;
            }
            ViewBag.CurrentFilter = s;

            var model = uow.jobRepository.GetAll();
            var jsmodel = new JobSearchViewModel();
            if (vm != null)
            {
                if (vm.JobSearchViewModel != null)
                    jsmodel = vm.JobSearchViewModel;
            }
            ViewBag.Sstr = "";
            if (!String.IsNullOrEmpty(s))
            {
                jsmodel.SearchString = s;
                ViewBag.Sstr = s;
            }

            ViewBag.Stt = "Job Location";
            if (!String.IsNullOrEmpty(st))
            {
                jsmodel.Location = st;
                ViewBag.Stt = st;
            }

            ViewBag.Cat = "Job Category";
            if (!String.IsNullOrEmpty(ct))
            {
                jsmodel.SearchString = ct;
                ViewBag.Cat = ct;
            }


            Dictionary<string, object> searchObj = JobModelToDict(jsmodel);
            model = jobService.FindJob(searchObj);

            switch (o)
            {
                case "salary_desc":
                    model = model.OrderByDescending(m => m.MaximumSalary);
                    break;
                case "popular":
                    model = model.OrderByDescending(m => m.NumberOfApplicants);
                    break;
                case "Date":
                    model = model.OrderBy(m => m.DatePosted);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(m => m.DatePosted);
                    break;
                default:  // Name ascending 
                    model = model.OrderByDescending(m => m.DatePosted);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (p ?? 1);
            var mod = new JobListVM
            {
                Jobs = model.ToPagedList(pageNumber, pageSize),
                JobSearchViewModel = jsmodel
            };


            int jobStartNum = GetJobStart(pageNumber, pageSize);
            int jobEndNum = GetJobEnd(model.Count(), pageNumber, pageSize, jobStartNum);
            ViewBag.StartIndex = jobStartNum;
            ViewBag.EndIndex = jobEndNum;
            ViewBag.ModelCount = model.Count();

            //ViewBag.JobCatId = uow.jobCategoryRepository.GetAll().AsEnumerable()
            //    .Select(j => new SelectListItem { Text = j.Name, Value = Convert.ToString(j.Jobs.Count()) });
            //ViewBag.State = CountryStates.GetStates("Nigeria");
            ViewBag.Companies = uow.companyRepository.GetAll().Select(c => c.Name);
            ViewBag.JobType = Enum.GetValues(typeof(JobType));
            ViewBag.ExperienceLevel = Enum.GetValues(typeof(ExperienceLevel));
            return View(mod);
        }

        #region out
        //private Dictionary<string, object> JobModelToDict(JobSearchModel jsmodel)
        //{
        //    Dictionary<string, object> result = new Dictionary<string, object>();
        //    foreach (PropertyInfo property in typeof(JobSearchModel).GetProperties())
        //    {
        //        var val = property.GetValue(jsmodel);
        //        if (val == null || String.IsNullOrEmpty(val.ToString()))
        //            continue;
        //        result.Add(property.Name, val);
        //    }
        //    return result;
        //}
        #endregion
        private Dictionary<string, object> JobModelToDict(JobSearchViewModel jsmodel)
        {
            Dictionary<string, object> result = new Dictionary<string, object>();
            foreach (PropertyInfo property in typeof(JobSearchViewModel).GetProperties())
            {
                var val = property.GetValue(jsmodel);
                if (val == null || String.IsNullOrEmpty(val.ToString()))
                    continue;
                result.Add(property.Name, val);
            }
            return result;
        }

        private int GetJobStart(int pageNumber, int pageSize)
        {
            return ((pageNumber - 1) * pageSize) + 1;
        }

        private int GetJobEnd(int T, int pageNumber, int pageSize, int startIndex)
        {
            if (T >= pageNumber * pageSize)
            {
                return pageNumber * pageSize;
            }
            else
            {
                return startIndex + (T - startIndex);
            }
        }


        [Authorize(Roles = "Company")]
        public ActionResult Post()
        {
            ViewBag.JobCatId = uow.jobCategoryRepository.GetAll().AsEnumerable()
                .Select(j => new SelectListItem { Text = j.Name, Value = j.ID.ToString() });
            ViewBag.JobType = new SelectList(Enum.GetValues(typeof(JobType)));
            //ViewBag.Location = CountryStates.GetStates("Nigeria");

JobPortal.App/Views/Job/Edit.cshtml
@model JobPortal.App.Models.PostJobViewModel

<section class=" job-bg ad-details-page">
    <div class="container">
        <div class="breadcrumb-section">
            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="index.html">Job</a></li>
                <li>Job Post </li>
            </ol><!-- breadcrumb -->
            <h2 class="title">Edit Job</h2>
        </div><!-- banner -->

        <div class="job-postdetails">
            <div class="row">
                <div class="col-md-8">
                    @using (Html.BeginForm("Edit", "Job", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary()
                        <fieldset>
                            <div class="section postdetails">
                            @Html.HiddenFor(m => m.Id)
                                <h4>Post Your Job<span class="pull-right">* Mandatory Fields</span></h4>
                                <div class="row form-group add-title">
                                    <label class="col-sm-3 label-title">Job Category</label>
                                    <div class="col-sm-9">
                                        @Html.DropDownList("JobCatId", null, "Select", new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <label class="col-sm-3 ">Job Type<span class="required">*</span></label>

                                    <div class="col-sm-9">
                                        @Html.DropDownList("Type", null, "Select", new { @class = "form-control" })
                                    </div>

                                </div>
                                <div class="row form-group">
                                    <label class="col-sm-3 label-title">Job Title<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @placeholder = "ex, Software Developer" })
                                    </div>
                                </div>
                                <div class="row form-group item-description">
                                    <label class="col-sm-3 label-title">Description<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Write few lines about your jobs", @rows = "8" })
                                    </div>
                                </div>
                                <div class="row characters">
                                    <div class="col-sm-9 col-sm-offset-3">
                                        <p>5000 characters left</p>
                                    </div>
                                </div>
                                <div class="row form-group add-title location">
                                    <label class="col-sm-3 label-title">State<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.DropDownList("State", null, "Select", new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="row form-group select-price">
                                    <label class="col-sm-3 label-title">Salary<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        <label>NGN</label>
                                        @Html.TextBoxFor(m => m.MinimumSalary, new { @class = "form-control", @placeholder = "Minimum" })
                                        <span>-</span>
                                        @Html.TextBoxFor(m => m.MaximumSalary, new { @class = "form-control", @placeholder = "Maximum" })
                                        @Html.CheckBoxFor(m => m.IsSalaryNegotiable)

                                        <label for="IsSalaryNegotiable">Negotiable </label>
                                    </div>
                                </div>

                                <div class="row form-group add-title">
                                    <label class="col-sm-3 label-title">Experience<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.DropDownList("ExperienceLevel", null, "Select", new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="row form-group add-title">
                                    <label class="col-sm-3 label-title">Deadline<span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.EditorFor(m => m.ApplicationDeadline)
                                    </div>
                                </div>
                                <div class="row form-group brand-name">
                                    <label class="col-sm-3 label-title">Required Skills <span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.TextAreaFor(m => m.RequiredSkills, new { @class = "form-control", @placeholder = "What skills do you require of the applicants?", @rows = "8" })
                                    </div>
                                </div>
                                <div class="row form-group brand-name">
                                    <label class="col-sm-3 label-title">Responsibilities <span class="required">*</span></label>
                                    <div class="col-sm-9">
                                        @Html.TextAreaFor(m => m.Responsibilities, new { @class = "form-control", @placeholder = "Job responsibilities", @rows = "8" })
                                    </div>
                                </div>
                            </div><!-- postdetails -->

                            <div class="checkbox section agreement">
                                <label for="send">
                                    <input type="checkbox" name="send" id="send">
                                    You agree to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a> and acknowledge that you are the rightful owner of this item and using Jobs to find a genuine buyer.
                                </label>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div><!-- section -->

                        </fieldset>
                    }


                </div>


                <!-- quick-rules -->
                <div class="col-md-4">
                    <div class="section quick-rules">
                        <h4>Quick rules</h4>
                        <p class="lead">Posting on <a href="http://www.thejobpitch.com">TheJobPitch.com</a> is currently free! However, all job ads must follow these rules:</p>

                        <ul>
                            <li>Make sure you post in the correct category.</li>
                            <li>Do not post the same ad more than once or repost an ad within 48 hours.</li>
                            <li>Do not upload pictures with watermarks.</li>
                            <li>Do not post ads containing multiple items unless it's a package deal.</li>
                            <li>Do not put your email or phone numbers in the title or description.</li>
                        </ul>
                    </div>
                </div><!-- quick-rules -->
            </div><!-- photos-ad -->
        </div>
    </div><!-- container -->
</section><!-- main -->

JobPortal.App/Views/Job/JobApplicants.cshtml
@model IEnumerable<JobPortal.Models.Implementation.JobApplication>

<section class=" job-bg page ad-profile-page">
    <div class="container">
        <div class="breadcrumb-section">
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li>Job Application</li>
            </ol>
            <h2 class="title">Applicants | @ViewBag.JobTitle</h2>
        </div><!-- breadcrumb-section -->

        <div class="section">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Profile Image</th>
                        <th>Applicant's Name</th>
                        <th>Profile Link</th>
                        <th>Pitch</th>
                    </tr>
                </thead>
                <tbody>
                    @{int count = 1; }
                    @foreach (var jobApp in Model)
                    {
        <tr>
            <td>@count</td>
            <td>
                <a class="pull-left" href="#">
                    <img src="@Url.Content(jobApp.user.Resume.ProfileImageUri)" class="media-object img-responsive img-rounded" style="width:150px; height:150px; margin-right:20px" />
                </a>
            </td>
            <td>@jobApp.user.Resume.FullName</td>
            <td>@Html.ActionLink("View full profile", "Details", "Profile", new { uid = jobApp.user.Id }, new { @class = "btn btn-primary" })</td>
            <td>
                @if (!String.IsNullOrEmpty(jobApp.pitchLocation))
                {
@Html.ActionLink("Watch video pitch", "WatchPitch", "Job", new { f = jobApp.pitchLocation }, new { @class = "btn btn-danger" })}
        </td>
    </tr>count++;
                }
                </tbody>
            </table>
        </div>



    </div>
</section>

JobPortal.App/Views/Job/Post.cshtml
@model JobPortal.App.Models.PostJobViewModel

<section class=" job-bg ad-details-page">
    <div class="container">
        <div class="breadcrumb-section">
            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="index.html">Job</a></li>
                <li>Job Post </li>
            </ol><!-- breadcrumb -->
            <h2 class="title">Post Your Job</h2>
        </div><!-- banner -->
  

        <div class="job-postdetails">
            <div class="row">
                <div class="col-md-8">
                   @using (Html.BeginForm("Post", "Job", FormMethod.Post))
                   {
                       @Html.AntiForgeryToken()
                    <fieldset>
                        <div class="section postdetails">
                            <h4>Post Your Job<span class="pull-right">* Mandatory Fields</span></h4>
                            <div class="row form-group add-title">
                                <label class="col-sm-3 label-title">Job Category</label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("JobCatId",null, "Select", new { @class = "form-control" })
                                    
                                </div>
                            </div>
                            <div class="row form-group">
                                <label class="col-sm-3 ">Job Type<span class="required">*</span></label>                            
                                <div class="col-sm-9">
                                    @Html.DropDownList("JobType", null, "Select", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.JobType)
                                </div>

                            </div>
                            <div class="row form-group">
                                <label class="col-sm-3 label-title">Job Title<span class="required">*</span></label>
                                <div class="col-sm-9">                                   
                                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control", @placeholder = "ex, Software Developer" })
                                    @Html.ValidationMessage("Title", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row form-group item-description">
                                <label class="col-sm-3 label-title">Description<span class="required">*</span></label>
                                <div class="col-sm-9">                                   
                                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control", @placeholder = "Write few lines about your jobs", @rows = "8" })                          
                                    @Html.ValidationMessage("Description", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row characters">
                                <div class="col-sm-9 col-sm-offset-3">
                                    @*<p>5000 characters left</p>*@
                                </div>
                            </div>
                            <div class="row form-group add-title location">
                                <label class="col-sm-3 label-title">State<span class="required">*</span></label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("State", null, "Select", new { @class = "form-control" })    
                                    @Html.ValidationMessage("State", new { @class = "text-danger" })                           
                                </div>
                            </div>
                            <div class="row form-group select-price">
                                <label class="col-sm-3 label-title">Salary<span class="required">*</span></label>
                                <div class="col-sm-9">
                                    <label>NGN</label>
                                    @Html.TextBoxFor(m => m.MinimumSalary, new { @class = "form-control", @placeholder = "Minimum" })                     
                                    <span>-</span>
                                    @Html.TextBoxFor(m => m.MaximumSalary, new { @class = "form-control", @placeholder = "Maximum" })                                                               
                                    @Html.CheckBoxFor(m => m.IsSalaryNegotiable)                                    
                                    <label for="IsSalaryNegotiable">Negotiable </label>

                                    @Html.ValidationMessage("MinimumSalary", new { @class = "text-danger" })
                                    @Html.ValidationMessage("MaximumSalary", new { @class = "text-danger" })
                                    
                                </div>
                            </div>
                    
                            <div class="row form-group add-title">
                                <label class="col-sm-3 label-title">Experience<span class="required">*</span></label>
                                <div class="col-sm-9">
                                    @Html.DropDownList("ExperienceLevel",null, "Select", new { @class = "form-control" })     
                                    @Html.ValidationMessage("ExperienceLevel", new { @class = "text-danger" })                             
                                </div>
                            </div>
                            <div class="row form-group add-title">
                                <label class="col-sm-3 label-title">Deadline<span class="required">*</span></label>
                                <div class="col-sm-9">
                                   @*@Html.EditorFor(m => m.ApplicationDeadline)*@
                                    <input type="date" name="ApplicationDeadline" class="form-control pull-right" value="@DateTime.Today.ToString("yyyy-MM-dd")">
                                    @Html.ValidationMessage("ApplicationDeadline", new { @class = "text-danger" })
                                    
                                </div>
                            </div>
                            <div class="row form-group brand-name">
                                <label class="col-sm-3 label-title">Required Skills <span class="required">*</span></label>
                                <div class="col-sm-9">                                    
                                    @Html.TextAreaFor(m => m.RequiredSkills, new { @class = "form-control", @placeholder = "What skill set do you require of the applicants?", @rows = "8" })
                                    @Html.ValidationMessage("RequiredSkills", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row form-group brand-name">
                                <label class="col-sm-3 label-title">Responsibilities <span class="required">*</span></label>
                                <div class="col-sm-9">
                                    @Html.TextAreaFor(m => m.Responsibilities, new { @class = "form-control", @placeholder = "Job responsibilities", @rows = "8" })
                                    @Html.ValidationMessage("Responsibilities", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div><!-- postdetails -->
                      <div>
                          @ViewBag.ErrorMsg
                      </div>
                        <div class="checkbox section agreement">
                            <label for="chksend">
                                <input type="checkbox"  name="chksend" id="chksend" onchange="chkTermsChanged()">
                                You agree to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>
                            </label>
                            <button type="submit" disabled class="btn btn-primary" id="btnPost">Post Your Job</button>
                        </div><!-- section -->

                        @*<div class="checkbox">
                            <label class="pull-left checked" for="signing-2"><input type="checkbox" name="signing-2" id="signing-2" onchange="chkTermsChanged()">By signing up for an account you agree to our Terms and Conditions</label>
                        </div>
                        <button type="submit" class="btn" id="btnRegCoy">Registration</button>*@

                    </fieldset>
                   }
                    
                    
                </div>


                <!-- quick-rules -->
                <div class="col-md-4">
                    <div class="section quick-rules">
                        <h4>Quick rules</h4>
                        <p class="lead">Posting an ad on <a href="http://www.thejobpitch.com">Thejobpitch.com</a> is free! However, all ads must follow our rules:</p>

                        <ul>
                            <li>Make sure you post in the correct category.</li>
                            <li>Do not post the same ad more than once or repost an ad within 48 hours.</li>
                            <li>Do not upload pictures with watermarks.</li>
                            <li>Do not post ads containing multiple items unless it's a package deal.</li>
                            <li>Do not put your email or phone numbers in the title or description.</li>
                        </ul>
                    </div>
                </div><!-- quick-rules -->
            </div><!-- photos-ad -->
        </div>
    </div><!-- container -->
</section><!-- main -->


<script type="text/javascript">
    function chkTermsChanged() {
     
      
        if (document.getElementById("chksend").checked) {
            document.getElementById("btnPost").disabled = false
        }
        else {
            document.getElementById("btnPost").disabled = true
        }

    }
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobPortal.App/Views/Job/_IJobList.cshtml
@model IEnumerable<JobPortal.Models.Implementation.Job>

@foreach (var item in Model)
{
<div class="job-ad-item">
    <div class="item-info">
        @*<div class="item-image-box col-sm-3">*@
        <div class="item-image-box">
            <div class="item-image">
                <a href="@Url.Action("details","job", new{id=@item.ID} )"> <img src="@Url.Content("~/assets/images/job/4.png")" alt="Image" class="img-responsive"> </a>
            </div><!-- item-image -->
        </div>

        <div class="ad-info">
            <span>@Html.ActionLink(@item.Title, "details", "Job", new { id = item.ID }, null)  @@ <a href="#">@item.Company.Name</a></span>
            <div class="ad-meta">
                <ul>
                    <li><i class="fa fa-map-marker" aria-hidden="true"></i>@item.State, @item.Country</li>
                    <li><i class="fa fa-clock-o" aria-hidden="true"></i>@item.Type.ToString()</li>
                    <li><i class="fa fa-money" aria-hidden="true"></i>NGN @item.MinimumSalary.ToString("N2") - NGN @item.MaximumSalary.ToString("N2")</li>
                </ul>
            </div><!-- ad-meta -->
        </div><!-- ad-info -->
    </div><!-- item-info -->
</div><!-- job-ad-item -->}